import {google} from 'googleapis'; import fs from 'node:fs';
const scopes=['https://www.googleapis.com/auth/calendar','https://www.googleapis.com/auth/drive'];
export function oauth(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI);}
export function authUrl(){return oauth().generateAuthUrl({access_type:'offline',prompt:'consent',scope:scopes});}
export async function exchange(code:string){const c=oauth(); const {tokens}=await c.getToken(code); return tokens;}
export function client(tokens:any){const c=oauth(); c.setCredentials(tokens); return c;}
export async function calendarList(tokens:any){const api=google.calendar({version:'v3',auth:client(tokens)}); const r=await api.events.list({calendarId:'primary',timeMin:new Date().toISOString(),maxResults:12,singleEvents:true,orderBy:'startTime'}); return r.data.items??[];}
export async function calendarCreate(tokens:any,p:any){const api=google.calendar({version:'v3',auth:client(tokens)}); const start=new Date(p.start).toISOString(); const end=new Date(p.end??new Date(new Date(start).getTime()+60*60*1000)).toISOString(); const r=await api.events.insert({calendarId:'primary',requestBody:{summary:p.title,description:p.description||'',start:{dateTime:start},end:{dateTime:end}}}); return r.data;}
export async function driveList(tokens:any, q?:string){const api=google.drive({version:'v3',auth:client(tokens)}); const query=q?`name contains '${q.replace(/'/g,"\\'")}' and trashed=false`:'trashed=false'; const r=await api.files.list({q:query,pageSize:50,fields:'files(id,name,mimeType,parents,modifiedTime,webViewLink,size)',orderBy:'modifiedTime desc'}); return r.data.files??[];}
export async function driveFolders(tokens:any){return driveList(tokens);}
export async function driveCreateFolder(tokens:any,name:string,parentId?:string){const api=google.drive({version:'v3',auth:client(tokens)}); const r=await api.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:parentId?[parentId]:undefined},fields:'id,name,mimeType,parents,webViewLink'}); return r.data;}
export async function driveUpload(tokens:any,file:any,parentId?:string){const api=google.drive({version:'v3',auth:client(tokens)}); const r=await api.files.create({requestBody:{name:file.originalname,parents:parentId?[parentId]:undefined},media:{mimeType:file.mimetype,body:fs.createReadStream(file.path)},fields:'id,name,mimeType,parents,modifiedTime,webViewLink'}); return r.data;}
